services: 
  mongo: 
    image: mongo
    networks: 
      - air
    restart : always
    ports: 
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
    
  backend:
    build: 
      context: ./backend
    
    restart: always
    ports: 
      - 8080:8080
    networks: 
      - air
    depends_on: 
      mongo: 
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/pollution/stats || exit 1"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment: 
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/PollutionDataSet
  
  # etlpipeline: 
  #   build:
  #     context: ./etl-pipeline
  #   networks: 
  #     - air-pollution-nw
  #   depends_on: 
  #     mongo: 
  #       condition: service_healthy
  #   restart: "no"
  #   environment: 
  #     SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/PollutionDataSet


networks: 
  air:
    driver: bridge
volumes:
  mongo-data:

