apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: grafana-pv 
spec: 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: grafana-storage 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /grafana 
    type: DirectoryOrCreate