apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: etl-application
  namespace: argocd
spec: 
  project: air-pollution-analytic-project
  source: 
    repoURL: https://github.com/arpanelfranklin/Air-Pollution-Analytic-Plateform.git
    targetRevision: main
    path: k8s/etl
  destination: 
    server: https://kubernetes.default.svc
    namespace: airpollution 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      