apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: prometheus-pv 
  labels: 
    app: prometheus-pv 
spec: 
  storageClassName: prometheus-storage
  capacity:
    storage: 5Gi 
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /prometheus
    type: DirectoryOrCreate