kind: Secret 
apiVersion: v1
metadata: 
  name: argocd-notification-secret 
  namespace: argocd
type: Opaque 
stringData: 
  email-username: arpanel.gdgbu@gmail.com 
  email-password: umbobiuetsxinfzj

