kind: Secret 
apiVersion: v1
metadata: 
  name: argocd-notifications-secret 
  namespace: argocd
type: Opaque 
stringData: 
  email-username: arpanelgdgbu@gmail.com 
  email-password: umbobiuetsxinfzj

